### ISSUE TITLE
Unable to generate HTML/PDF output

### ISSUE THREAD

**Issue by DeserranoJorden** [1modm/petereport#3]
Hey,

I'm currently testing this application through the docker setup.
The only thing that is not working for me is HTML/PDF generation.

I get the following error when trying to generate one from a test report 

```
petereport_1  | Internal Server Error: /report/download/pdf/1
petereport_1  | Traceback (most recent call last):
petereport_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
petereport_1  |     response = get_response(request)
petereport_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
petereport_1  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
petereport_1  |   File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
petereport_1  |     return view_func(request, *args, **kwargs)
petereport_1  |   File "/opt/petereport/app/preport/views.py", line 899, in reportdownloadpdf
petereport_1  |     output_pypandoc = pypandoc.convert_text(final_markdown_output, to='pdf', outputfile=pdf_file_output, format='md', extra_args=['-H', PDF_HEADER_FILE, '--from', 'markdown+yaml_metadata_block+raw_html', '--template', PETEREPORT_LATEX_FILE, '--table-of-contents', '--toc-depth', '4', '--number-sections', '--highlight-style', 'breezedark', '--filter', 'pandoc-latex-environment', '--listings'])
petereport_1  |   File "/usr/local/lib/python3.8/dist-packages/pypandoc/__init__.py", line 100, in convert_text
petereport_1  |     return _convert_input(source, format, 'string', to, extra_args=extra_args,
petereport_1  |   File "/usr/local/lib/python3.8/dist-packages/pypandoc/__init__.py", line 321, in _convert_input
petereport_1  |     raise RuntimeError(
petereport_1  | RuntimeError: Pandoc died with exitcode "1" during conversion: b'pandoc: /opt/petereport/app/storage_reports/pdf/PEN-PDF_Fabriekse_202111040921.pdf: openBinaryFile: does not exist (No such file or directory)\n'
```

The map /opt/petereport/app/storage_reports also does not exist on the docker image.
Is there anything else I do need to setup for this?

**Comment by 1modm** [comment]
Sorry my fault, empty folders not pushed to the repo.

Fixed. Stop docker, git pull and start again.

Thanks

**Comment by DeserranoJorden** [comment]
Thanks!
